// Administrator actions - Manage Products
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING";
export const CLEAR_FEEDBACK_MESSAGE = "CLEAR_FEEDBACK_MESSAGE";
