// Administrator actions - Manage Products
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_ERROR = "REMOVE_PRODUCT_ERROR";
export const CLEAR_FEEDBACK_MESSAGE = "CLEAR_FEEDBACK_MESSAGE";

// Guest actions
export const GET_PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_LIST_SUCCESS";
export const GET_PRODUCTS_LIST_ERROR = "GET_PRODUCTS_LIST_ERROR";
export const GET_PRODUCTS_LIST_LOADING = "GET_PRODUCTS_LIST_LOADING";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";
