// Administrator actions - Manage Products
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_ERROR = "REMOVE_PRODUCT_ERROR";
export const CLEAR_FEEDBACK_MESSAGE = "CLEAR_FEEDBACK_MESSAGE";

// Administrator actions - Manage Orders
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR";

// Guest actions
export const GET_PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_LIST_SUCCESS";
export const GET_PRODUCTS_LIST_ERROR = "GET_PRODUCTS_LIST_ERROR";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const GET_PRODUCTS_LIST_LOADING = "GET_PRODUCTS_LIST_LOADING";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";

// Search actions
export const CLEAN_QUERY = "CLEAN_QUERY";
export const START_SEARCH = "START_SEARCH";
export const FINISH_SEARCH = "FINISH_SEARCH";
export const UPDATE_SELECTION = "UPDATE_SELECTION";

// Shopping cart actions
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_ACTION_LOADING = "CART_ACTION_LOADING";
export const CLEAR_CART = "CLEAR_CART";

// Checkout actions - Step 1
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_DELIVERY_ADDRESS = "SET_DELIVERY_ADDRESS";
export const SET_DELIVERY_METHOD = "SET_DELIVERY_METHOD";

// Checkout actions - Step 2
export const SET_CARD_NUMBER = "SET_CARD_NUMBER";
export const SET_CARDHOLDER_NAME = "SET_CARDHOLDER_NAME";
export const SET_SECURITY_CODE = "SET_SECURITY_CODE";
export const SET_EXPIRY_MONTH = "SET_EXPIRY_MONTH";
export const SET_EXPIRY_YEAR = "SET_EXPIRY_YEAR";

// Checkout actions - Step 3
export const SET_TC_AGREEMENT = "SET_TC_AGREEMENT";
export const SET_TOTAL_COST = "SET_TOTAL_COST";

// Checkout actions - Clear state
export const CLEAR_STATE = "CLEAR_STATE";

// Form validation actions - Step 1
export const STEP_1_VALIDATION_ERROR = "STEP_1_VALIDATION_ERROR";
export const STEP_2_VALIDATION_ERROR = "STEP_2_VALIDATION_ERROR";
export const STEP_3_VALIDATION_ERROR = "STEP_3_VALIDATION_ERROR";
export const SET_VALIDATOR_LOADING = "SET_VALIDATOR_LOADING";
export const CLEAR_VALIDATION_ERROR_MSG = "CLEAR_VALIDATION_ERROR_MSG";

// Order actions for user
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_ERROR = "GET_USER_ORDERS_ERROR";

// Order actions for user and administrator
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_ERROR = "CANCEL_ORDER_ERROR";
